'use strict';
const encoder=new TextEncoder();
const table=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});
function crc(bytes){let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function header(size,fields){const b=new Uint8Array(size),v=new DataView(b.buffer);for(const [at,value,width]of fields)width===4?v.setUint32(at,value,true):v.setUint16(at,value,true);return b}
async function zipPhotos(photos,onProgress){const chunks=[],central=[];let offset=0;for(let i=0;i<photos.length;i++){onProgress(i+1);const res=await fetch(photos[i].url);if(!res.ok)throw Error('Photo download failed');const b=new Uint8Array(await res.arrayBuffer()),name=encoder.encode(photos[i].name),sum=crc(b);const h=header(30,[[0,0x04034b50,4],[4,20,2],[14,sum,4],[18,b.length,4],[22,b.length,4],[26,name.length,2]]);chunks.push(h,name,b);central.push(header(46,[[0,0x02014b50,4],[4,20,2],[6,20,2],[16,sum,4],[20,b.length,4],[24,b.length,4],[28,name.length,2],[42,offset,4]]),name);offset+=h.length+name.length+b.length}const total=central.reduce((n,b)=>n+b.length,0);return new Blob([...chunks,...central,header(22,[[0,0x06054b50,4],[8,photos.length,2],[10,photos.length,2],[12,total,4],[16,offset,4]])],{type:'application/zip'})}
fetch('gallery-data.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(albums=>{for(const album of albums){const section=document.querySelector(`[data-album="${album.slug}"]`),img=section.querySelector('.slide'),counter=section.querySelector('.counter'),download=section.querySelector('a.download'),status=section.querySelector('.status'),play=section.querySelector('[data-action="play"]');let index=0,timer=null,start=0;
function show(n){index=(n+album.photos.length)%album.photos.length;const p=album.photos[index];img.src=p.view;img.alt=`Awuah Wedding ${album.label}, photo ${index+1}`;counter.textContent=`Photo ${index+1} of ${album.photos.length}`;download.href=p.url;download.download=p.name;const next=new Image();next.src=album.photos[(index+1)%album.photos.length].view}
function stop(){clearInterval(timer);timer=null;play.textContent='Play Slideshow'}
section.querySelector('[data-action="previous"]').onclick=()=>{stop();show(index-1)};section.querySelector('[data-action="next"]').onclick=()=>{stop();show(index+1)};play.onclick=()=>{if(timer)stop();else{timer=setInterval(()=>show(index+1),1000);play.textContent='Pause Slideshow'}};
section.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();stop();show(index+(e.key==='ArrowRight'?1:-1))}});img.addEventListener('touchstart',e=>start=e.changedTouches[0].clientX,{passive:true});img.addEventListener('touchend',e=>{const delta=e.changedTouches[0].clientX-start;if(Math.abs(delta)>50){stop();show(index+(delta<0?1:-1))}},{passive:true});
section.querySelector('[data-action="all"]').onclick=async function(){this.disabled=true;stop();try{const blob=await zipPhotos(album.photos,n=>status.textContent=`Preparing photo ${n} of ${album.photos.length}… Please keep this page open.`);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Awuah-Wedding-${album.label.replaceAll(" ","-")}.zip`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent='Your album ZIP is ready. Check your downloads.'}catch(e){status.textContent='Unable to prepare the full album. Please try again or download individual photos.'}finally{this.disabled=false}};show(0)}}).catch(()=>{document.querySelector('main').insertAdjacentHTML('beforeend','<p>Unable to load the albums. Please refresh this page.</p>')});
